[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17"
optimizer_runs = 999999
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
